name: Build QMK Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install QMK and Dependencies
        run: |
          python3 -m pip install --user qmk==1.1.5
          qmk setup -y
          
      - name: Build Firmware
        run: |
          cd qmk/qmk_firmware
          cp -r ../../keyboards/crkbd/qmk/qmk_firmware/keyboards/crkbd/* ./keyboards/crkbd/
          qmk compile -kb crkbd/rev4_1/standard -km vial
          cp ./.build/*.uf2 ../../

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: corne_v4_firmware
          path: ./*.uf2
